#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Oct 01, 2021 05:15:17 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import RSA_Gui
import Elgamal_Gui
import Pailler_Gui

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def openRSAWindow():
    destroy_window()
    RSA_Gui.RSA_Windows()

def openElgamalWindow():
    destroy_window()
    Elgamal_Gui.Elgamal_windows()

def openPaillierWindow():
    destroy_window()
    Pailler_Gui.Pailler_Windows()

